const matchingWord = [
  {
    id: 1,
    english: "accept",
    turkish: "kabul etmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 2,
    english: "achieve",
    turkish: "başarmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 3,
    english: "acquire",
    turkish: "edinmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 4,
    english: "add",
    turkish: "eklemek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 5,
    english: "address",
    turkish: "hitap etmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 6,
    english: "admit",
    turkish: "itiraf etmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 7,
    english: "advise",
    turkish: "önermek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 8,
    english: "affect",
    turkish: "etkilemek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 9,
    english: "agree",
    turkish: "katılmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 10,
    english: "allow",
    turkish: "izin vermek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 11,
    english: "analyse",
    turkish: "analiz etmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 12,
    english: "answer",
    turkish: "cevaplamak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 13,
    english: "appear",
    turkish: "ortaya çıkmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 14,
    english: "appoint",
    turkish: "ayarlamak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 15,
    english: "approve",
    turkish: "onaylamak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 16,
    english: "argue",
    turkish: "tartışmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 17,
    english: "arrange",
    turkish: "ayarlamak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 18,
    english: "arrest",
    turkish: "tutuklamak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 19,
    english: "arrive",
    turkish: "varmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 20,
    english: "ask",
    turkish: "sormak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 21,
    english: "back",
    turkish: "yardım etmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 22,
    english: "be",
    turkish: "olmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 23,
    english: "become",
    turkish: "olmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 24,
    english: "begin",
    turkish: "başlamak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 25,
    english: "believe",
    turkish: "inanmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 26,
    english: "born",
    turkish: "doğmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 27,
    english: "break",
    turkish: "kırmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 28,
    english: "bring",
    turkish: "getirmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 29,
    english: "build",
    turkish: "inşa etmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 30,
    english: "burn",
    turkish: "yanmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 31,
    english: "buy",
    turkish: "satın almak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 32,
    english: "call",
    turkish: "aramak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 33,
    english: "care",
    turkish: "ilgilenmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 34,
    english: "carry",
    turkish: "taşımak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 35,
    english: "catch",
    turkish: "yakalamak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 36,
    english: "cause",
    turkish: "sebep olmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 37,
    english: "change",
    turkish: "değiştirmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 38,
    english: "check",
    turkish: "bakmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 39,
    english: "choose",
    turkish: "seçmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 40,
    english: "claim",
    turkish: "istemek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 41,
    english: "clean",
    turkish: "temizlemek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 42,
    english: "climb",
    turkish: "tırmanmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 43,
    english: "close",
    turkish: "kapatmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 44,
    english: "combine",
    turkish: "birleştirmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 45,
    english: "come",
    turkish: "gelmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 46,
    english: "comment",
    turkish: "yorumlamak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 47,
    english: "compare",
    turkish: "karşılaştırmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 48,
    english: "confirm",
    turkish: "onaylamak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 49,
    english: "connect",
    turkish: "bağlanmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 50,
    english: "consider",
    turkish: "düşünmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 51,
    english: "contain",
    turkish: "kapsamak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 52,
    english: "continue",
    turkish: "devam etmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 53,
    english: "control",
    turkish: "kontrol etmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 54,
    english: "cook",
    turkish: "pişirmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 55,
    english: "count",
    turkish: "saymak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 56,
    english: "cover",
    turkish: "örtmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 57,
    english: "create",
    turkish: "yaratmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 58,
    english: "cry",
    turkish: "ağlamak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 59,
    english: "cut",
    turkish: "kesmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 60,
    english: "damage",
    turkish: "zedelemek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 61,
    english: "dance",
    turkish: "dans etmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 62,
    english: "deal",
    turkish: "anlaşmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 63,
    english: "decide",
    turkish: "karar vermek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 64,
    english: "define",
    turkish: "açıklamak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 65,
    english: "deliver",
    turkish: "göndermek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 66,
    english: "depend",
    turkish: "bağlanmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 67,
    english: "describe",
    turkish: "açıklamak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 68,
    english: "design",
    turkish: "tasarlamak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 69,
    english: "destroy",
    turkish: "yok etmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 70,
    english: "determine",
    turkish: "belirtmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 71,
    english: "develop",
    turkish: "geliştirmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 72,
    english: "die",
    turkish: "ölmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 73,
    english: "direct",
    turkish: "yönlendirmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 74,
    english: "disappear",
    turkish: "kaybolmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 75,
    english: "discover",
    turkish: "keşfetmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 76,
    english: "discuss",
    turkish: "tartışmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 77,
    english: "do",
    turkish: "yapmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 78,
    english: "dress",
    turkish: "giyinmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 79,
    english: "drink",
    turkish: "içmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 80,
    english: "drive",
    turkish: "kullanmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 81,
    english: "earn",
    turkish: "kazanmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 82,
    english: "eat",
    turkish: "yemek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 83,
    english: "end",
    turkish: "bitirmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 84,
    english: "enter",
    turkish: "girmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 85,
    english: "escape",
    turkish: "kaçmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 86,
    english: "exercise",
    turkish: "egzersiz yapmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 87,
    english: "explain",
    turkish: "açıklamak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 88,
    english: "explore",
    turkish: "keşfetmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 89,
    english: "face",
    turkish: "yüzleşmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 90,
    english: "fail",
    turkish: "başarısız olmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 91,
    english: "fear",
    turkish: "korkmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 92,
    english: "feed",
    turkish: "beslemek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 93,
    english: "feel",
    turkish: "hissetmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 94,
    english: "fight",
    turkish: "savaşmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 95,
    english: "find",
    turkish: "bulmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 96,
    english: "finish",
    turkish: "bitirmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 97,
    english: "fly",
    turkish: "uçmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 98,
    english: "focus",
    turkish: "odaklanmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 99,
    english: "follow",
    turkish: "takip etmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 100,
    english: "force",
    turkish: "zorlamak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 101,
    english: "forget",
    turkish: "unutmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 102,
    english: "get",
    turkish: "almak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 103,
    english: "give",
    turkish: "vermek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 104,
    english: "go",
    turkish: "gitmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 105,
    english: "grow",
    turkish: "büyümek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 106,
    english: "handle",
    turkish: "halletmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 107,
    english: "hang",
    turkish: "asmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 108,
    english: "happen",
    turkish: "olmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 109,
    english: "hate",
    turkish: "nefret etmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 110,
    english: "have",
    turkish: "sahip olmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 111,
    english: "hear",
    turkish: "duymak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 112,
    english: "help",
    turkish: "yardım etmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 113,
    english: "hide",
    turkish: "saklamak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 114,
    english: "hit",
    turkish: "vurmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 115,
    english: "hold",
    turkish: "tutmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 116,
    english: "hope",
    turkish: "ummak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 117,
    english: "hurt",
    turkish: "incitmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 118,
    english: "identify",
    turkish: "tanımlamak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 119,
    english: "imagine",
    turkish: "hayal etmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 120,
    english: "improve",
    turkish: "geliştirmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 121,
    english: "include",
    turkish: "içermek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 122,
    english: "increase",
    turkish: "arttırmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 123,
    english: "indicate",
    turkish: "belirtmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 124,
    english: "inform",
    turkish: "bildirmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 125,
    english: "inject",
    turkish: "enjekte etmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 126,
    english: "insist",
    turkish: "ısrar etmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 127,
    english: "install",
    turkish: "kurmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 128,
    english: "introduce",
    turkish: "tanıtmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 129,
    english: "invest",
    turkish: "yatırım yapmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 130,
    english: "invite",
    turkish: "davet etmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 131,
    english: "join",
    turkish: "katılmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 132,
    english: "jump",
    turkish: "atlamak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 133,
    english: "keep",
    turkish: "saklamak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 134,
    english: "kick",
    turkish: "tekmelemek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 135,
    english: "kill",
    turkish: "öldürmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 136,
    english: "kiss",
    turkish: "öpüşmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 137,
    english: "know",
    turkish: "bilmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 138,
    english: "laugh",
    turkish: "gülmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 139,
    english: "learn",
    turkish: "öğrenmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 140,
    english: "leave",
    turkish: "ayrılmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 141,
    english: "lend",
    turkish: "ödünç vermek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 142,
    english: "lie",
    turkish: "yalan söylemek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 143,
    english: "like",
    turkish: "beğenmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 144,
    english: "listen",
    turkish: "dinlemek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 145,
    english: "live",
    turkish: "yaşamak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 146,
    english: "look",
    turkish: "bakmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 147,
    english: "lose",
    turkish: "kaybetmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 148,
    english: "love",
    turkish: "sevmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 149,
    english: "make",
    turkish: "yapmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 150,
    english: "manage",
    turkish: "yönetmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 151,
    english: "mark",
    turkish: "işaretlemek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 152,
    english: "marry",
    turkish: "evlenmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 153,
    english: "matter",
    turkish: "önemli olmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 154,
    english: "mean",
    turkish: "anlamına gelmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 155,
    english: "meet",
    turkish: "tanışmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 156,
    english: "mention",
    turkish: "bahsetmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 157,
    english: "mind",
    turkish: "önemsemek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 158,
    english: "miss",
    turkish: "özlemek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 159,
    english: "move",
    turkish: "hareket etmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 160,
    english: "need",
    turkish: "ihtiyaç duymak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 161,
    english: "notice",
    turkish: "farkına varmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 162,
    english: "observe",
    turkish: "gözlemlemek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 163,
    english: "obtain",
    turkish: "elde etmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 164,
    english: "offer",
    turkish: "teklif etmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 165,
    english: "open",
    turkish: "açmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 166,
    english: "order",
    turkish: "sipariş vermek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 167,
    english: "organize",
    turkish: "düzenlemek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 168,
    english: "own",
    turkish: "sahip olmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 169,
    english: "paint",
    turkish: "boyamak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 170,
    english: "participate",
    turkish: "katılmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 171,
    english: "pay",
    turkish: "ödemek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 172,
    english: "perform",
    turkish: "yerine getirmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 173,
    english: "plan",
    turkish: "planlamak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 174,
    english: "play",
    turkish: "oynamak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 175,
    english: "point",
    turkish: "işaret etmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 176,
    english: "possess",
    turkish: "sahip olmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 177,
    english: "practice",
    turkish: "çalışmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 178,
    english: "prefer",
    turkish: "tercih etmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 179,
    english: "prepare",
    turkish: "hazırlamak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 180,
    english: "present",
    turkish: "sunmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 181,
    english: "prevent",
    turkish: "önlemek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 182,
    english: "produce",
    turkish: "üretmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 183,
    english: "protect",
    turkish: "korumak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 184,
    english: "provide",
    turkish: "sağlamak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 185,
    english: "publish",
    turkish: "yayınlamak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 186,
    english: "pull",
    turkish: "çekmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 187,
    english: "push",
    turkish: "itmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 188,
    english: "put",
    turkish: "koymak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 189,
    english: "raise",
    turkish: "yükseltmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 190,
    english: "reach",
    turkish: "ulaşmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 191,
    english: "realize",
    turkish: "farkına varmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 192,
    english: "receive",
    turkish: "teslim almak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 193,
    english: "recognize",
    turkish: "tanımak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 194,
    english: "record",
    turkish: "kaydetmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 195,
    english: "reduce",
    turkish: "azaltmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 196,
    english: "reflect",
    turkish: "yansıtmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 197,
    english: "refuse",
    turkish: "reddetmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 198,
    english: "regret",
    turkish: "pişman olmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 199,
    english: "relax",
    turkish: "rahatlamak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 200,
    english: "release",
    turkish: "serbest bırakmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 201,
    english: "rely",
    turkish: "güvenmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 202,
    english: "remain",
    turkish: "kalmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 203,
    english: "remember",
    turkish: "hatırlamak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 204,
    english: "remove",
    turkish: "kaldırmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 205,
    english: "repair",
    turkish: "onarmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 206,
    english: "repeat",
    turkish: "tekrarlamak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 207,
    english: "replace",
    turkish: "yerini almak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 208,
    english: "reply",
    turkish: "cevap vermek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 209,
    english: "report",
    turkish: "bildirmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 210,
    english: "represent",
    turkish: "temsil etmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 211,
    english: "request",
    turkish: "talep etmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 212,
    english: "require",
    turkish: "gerektirmek",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
  {
    id: 213,
    english: "rescue",
    turkish: "kurtarmak",
    done: false,
    clickEng: false,
    clickTur: false,
    matched: false,
  },
];

export default matchingWord;
